#!/bin/sh

mkdir -p /var/lib/get-out

# create get_out group
if ! getent group get_out >/dev/null; then
        addgroup --system get_out
fi

# create get_out user
if ! getent passwd get_out >/dev/null; then
        adduser --system --ingroup get_out --home /var/lib/get-out \
                --no-create-home --gecos "get-out server" \
                --disabled-login get_out
fi

chown -R get_out:get_out /var/lib/get-out
chown get_out:get_out /etc/get-out/config

